/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'partsaleva' at '6/4/16 1:26 PM' with Gradle 2.13
 *
 * @author partsaleva, @date 6/4/16 1:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
